# Base image
FROM python:3.9-slim

# Set work directory
WORKDIR /app

# Install required packages
RUN pip install kafka-python redis requests

# Copy the script
COPY producer.py /app/producer.py

CMD ["python", "producer.py"]
